import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner
        title="Clifford the red dog"
        subTitle="Raising her daughter in the small town of Middleton, an enchanting widow with magical powers provokes the interest and exasperation of a big-city doctor."
        imgUrl="/static/clifford.jpg"
      />
      <div style={{ height: "300vh" }}></div>
    </>
  );
}


